apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tshirt-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 816546948694.dkr.ecr.ap-south-1.amazonaws.com/tshirt-shop-api:fa9750c
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-db-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
